### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by 2fd** [2fd/graphdoc#69]
## Version 3
* [ ] move project to  [`@graphdoc`](https://github.com/graphdoc) organization
* [ ] move package to [`@graphdoc`](https://www.npmjs.com/~graphdoc) namespace in npm
* [ ] custom domain [`https://graphdoc.dev`](https://graphdoc.dev) (?)
* [ ] dependency changes
  * [ ] use [`oclif`](https://oclif.io/) for cli
  * [ ] use [`react`](https://reactjs.org/) for templating
* [ ] re-struct the project as a mono-repo and separate functionalities
  * [ ] `@graphdoc/cli`: cli implementation
  * [ ] `@graphdoc/components`: react components to render each documentation section
  * [ ] `@graphdoc/source-{http,json,...}`: logic to download/load the introspection query
  * [ ] `@graphdoc/output-{html,md,ts,flow,...}`: logic to generate output
* [ ] integration with other services and documentation tools
  * [ ] [`docusaurus`](https://docusaurus.io/)
  * [ ] [`apollo`](https://www.apollographql.com/) (?)
  * [ ] [`gatsbyjs`](https://www.gatsbyjs.org) (?)

## Version 2.5
* [ ] update dependencies
* [ ] merge pull request
* [ ] fix reported errors
